### ISSUE TITLE
Question: maintenance status and … does it fit my needs?

### ISSUE THREAD

**Issue by julianklotz** [rob-metalinkage/django-rdf-io#20]
Hi Rob,

When I was looking for ways to synchronize Django models with another database, I found your project. Thank you for offering it open source!

As far as I can tell, it is exactly what I need:

* When creating or changing an object, the object should be serialized and written to the database (GraphDB). For serialization, I would like to be able to define a ruleset for my object types.

* When deleting an object, the object should be deleted from the graph (e.g. through a context or a named graph).

Is this module suitable for this? Do you plan to maintain the project in the long term?

Thanks and greetings
Julian

**Comment by rob-metalinkage** [comment]
Hi julian
the answer is .. possibly..

it is maintained ... 

It generates RDF graphs using RDFLIB - then passes this to a configurable chain of services  - so should e fine to push to GraphDB - but may need some love to create a "serviceBinding" - currently supports RDF4J and LPD, pushing whole containers.  Should be fine to push instances if the API supports this.

At the moment no deletion handling is in place - because I use it to maintain contexts (graphs) on a replace basis - but this isnt a huge deal.

Getting tests against different repo APIS will be a challenge, ideas welcome.

**Comment by julianklotz** [comment]
Hi Rob,

thanks – that helped me a lot. Turns out GraphDB exposes the underlying RDF4J’s REST API. Let’s see.

Have a nice weekend

**Comment by rob-metalinkage** [comment]
OK - I will improve the examples of how to use RDF4J :-)
